export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const FETCH_ROBOTS_PENDING = 'FETCH_ROBOTS_PENDING';
export const FETCH_ROBOTS_READY = 'FETCH_ROBOTS_READY';
export const FETCH_ROBOTS_FAILED = 'FETCH_ROBOTS_FAILED';